name: web_agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - ollama-python==0.1.2
      - ddgs==9.4.0
      - langchain-openai==0.3.27
      - langchain-community==0.3.27
      - openai==1.86.0
      - langchain==0.3.26
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - jupyter==1.1.1
      - ipykernel==6.29.5